name: sip scraper

on: [workflow dispetch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Main py
        run: python main.py takepicture.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update novosti.md
        id: auto-commit-action

      - name: Discord bot
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python discord.py
        
